"""add audit logs table

Revision ID: 4d04fdbe54be
Revises: 60530f65cd1a
Create Date: 2026-03-05 10:42:06.356579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d04fdbe54be'
down_revision = '60530f65cd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=False))
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('performed_by',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('audit_logs_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('bgv_id')
        batch_op.drop_column('description')

    with op.batch_alter_table('verification_types', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('name'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('bgv_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('audit_logs_ibfk_1'), 'bgv_requests', ['bgv_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('performed_by',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    # ### end Alembic commands ###
