"""add is_active to verification_types

Revision ID: 5ed6d5f57e25
Revises: 4d04fdbe54be
Create Date: 2026-03-05 12:21:50.404217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed6d5f57e25'
down_revision = '4d04fdbe54be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_types', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
